# This is the example config for our server.
# The settings here match those in the installation instructions and should be enough to get you up and running.

host:
  title: "ida A1200"
  hostname: "ida - development"
  computer: "Amiga A1200 68030 @ 55MHz"

server:
  port: 8080
  static: ui/dist

# List of available FAT32 volumes.
# Normally you only have one available but multiple volumes are supported.
volume:
  - mount: "/mnt/usb_share"
    device: "/piusb.bin"
