# This is the example config for our server.
# The settings here match those in the installation instructions and should be enough to get you up and running.

node:
  hostname: "ida - development"

server:
  port: 8080
  static: ui/dist

volume:
  # The mount point for our VFAT formatted volume
  path: "/home/peter/tmpDisk"
  # Command to mount the storage onto the gotek
  mount: ""
  # Command to unmount the storage so the gotek cannot access it anymore
  umount: ""
